microsoft_hresult_facilities! {
    #define FACILITY_ NULL                    0
    #define FACILITY_ RPC                     1
    #define FACILITY_ DISPATCH                2
    #define FACILITY_ STORAGE                 3
    #define FACILITY_ ITF                     4
    #define FACILITY_ WIN32                   7
    #define FACILITY_ WINDOWS                 8
    #define FACILITY_ SSPI                    9
    #define FACILITY_ SECURITY                9
    #define FACILITY_ CONTROL                 10
    #define FACILITY_ CERT                    11
    #define FACILITY_ INTERNET                12
    #define FACILITY_ MEDIASERVER             13
    #define FACILITY_ MSMQ                    14
    #define FACILITY_ SETUPAPI                15
    #define FACILITY_ SCARD                   16
    #define FACILITY_ COMPLUS                 17
    #define FACILITY_ AAF                     18
    #define FACILITY_ URT                     19
    #define FACILITY_ ACS                     20
    #define FACILITY_ DPLAY                   21
    #define FACILITY_ UMI                     22
    #define FACILITY_ SXS                     23
    #define FACILITY_ WINDOWS_CE              24
    #define FACILITY_ HTTP                    25
    #define FACILITY_ USERMODE_COMMONLOG      26
    #define FACILITY_ WER                     27
    #define FACILITY_ USERMODE_FILTER_MANAGER 31
    #define FACILITY_ BACKGROUNDCOPY          32
    #define FACILITY_ CONFIGURATION           33
    #define FACILITY_ WIA                     33
    #define FACILITY_ STATE_MANAGEMENT        34
    #define FACILITY_ METADIRECTORY           35
    #define FACILITY_ WINDOWSUPDATE           36
    #define FACILITY_ DIRECTORYSERVICE        37
    #define FACILITY_ GRAPHICS                38
    #define FACILITY_ SHELL                   39
    #define FACILITY_ NAP                     39
    #define FACILITY_ TPM_SERVICES            40
    #define FACILITY_ TPM_SOFTWARE            41
    #define FACILITY_ UI                      42
    #define FACILITY_ XAML                    43
    #define FACILITY_ ACTION_QUEUE            44
    #define FACILITY_ PLA                     48
    #define FACILITY_ WINDOWS_SETUP           48
    #define FACILITY_ FVE                     49
    #define FACILITY_ FWP                     50
    #define FACILITY_ WINRM                   51
    #define FACILITY_ NDIS                    52
    #define FACILITY_ USERMODE_HYPERVISOR     53
    #define FACILITY_ CMI                     54
    #define FACILITY_ USERMODE_VIRTUALIZATION 55
    #define FACILITY_ USERMODE_VOLMGR         56
    #define FACILITY_ BCD                     57
    #define FACILITY_ USERMODE_VHD            58
    #define FACILITY_ USERMODE_HNS            59
    #define FACILITY_ SDIAG                   60
    #define FACILITY_ WEBSERVICES             61
    #define FACILITY_ WINPE                   61
    #define FACILITY_ WPN                     62
    #define FACILITY_ WINDOWS_STORE           63
    #define FACILITY_ INPUT                   64
    #define FACILITY_ QUIC                    65
    #define FACILITY_ EAP                     66
    #define FACILITY_ WINDOWS_DEFENDER        80
    #define FACILITY_ OPC                     81
    #define FACILITY_ XPS                     82
    #define FACILITY_ MBN                     84
    #define FACILITY_ POWERSHELL              84
    #define FACILITY_ RAS                     83
    #define FACILITY_ P2P_INT                 98
    #define FACILITY_ P2P                     99
    #define FACILITY_ DAF                     100
    #define FACILITY_ BLUETOOTH_ATT           101
    #define FACILITY_ AUDIO                   102
    #define FACILITY_ STATEREPOSITORY         103
    #define FACILITY_ VISUALCPP               109
    #define FACILITY_ SCRIPT                  112
    #define FACILITY_ PARSE                   113
    #define FACILITY_ BLB                     120
    #define FACILITY_ BLB_CLI                 121
    #define FACILITY_ WSBAPP                  122
    #define FACILITY_ BLBUI                   128
    #define FACILITY_ USN                     129
    #define FACILITY_ USERMODE_VOLSNAP        130
    #define FACILITY_ TIERING                 131
    #define FACILITY_ WSB_ONLINE              133
    #define FACILITY_ ONLINE_ID               134
    #define FACILITY_ DEVICE_UPDATE_AGENT     135
    #define FACILITY_ DRVSERVICING            136
    #define FACILITY_ DLS                     153
    #define FACILITY_ DELIVERY_OPTIMIZATION   208
    #define FACILITY_ USERMODE_SPACES         231
    #define FACILITY_ USER_MODE_SECURITY_CORE 232
    #define FACILITY_ USERMODE_LICENSING      234
    #define FACILITY_ SOS                     160
    #define FACILITY_ DEBUGGERS               176
    #define FACILITY_ SPP                     256
    #define FACILITY_ RESTORE                 256
    #define FACILITY_ DMSERVER                256
    #define FACILITY_ DEPLOYMENT_SERVICES_SERVER 257
    #define FACILITY_ DEPLOYMENT_SERVICES_IMAGING 258
    #define FACILITY_ DEPLOYMENT_SERVICES_MANAGEMENT 259
    #define FACILITY_ DEPLOYMENT_SERVICES_UTIL 260
    #define FACILITY_ DEPLOYMENT_SERVICES_BINLSVC 261
    #define FACILITY_ DEPLOYMENT_SERVICES_PXE 263
    #define FACILITY_ DEPLOYMENT_SERVICES_TFTP 264
    #define FACILITY_ DEPLOYMENT_SERVICES_TRANSPORT_MANAGEMENT 272
    #define FACILITY_ DEPLOYMENT_SERVICES_DRIVER_PROVISIONING 278
    #define FACILITY_ DEPLOYMENT_SERVICES_MULTICAST_SERVER 289
    #define FACILITY_ DEPLOYMENT_SERVICES_MULTICAST_CLIENT 290
    #define FACILITY_ DEPLOYMENT_SERVICES_CONTENT_PROVIDER 293
    #define FACILITY_ LINGUISTIC_SERVICES     305
    #define FACILITY_ AUDIOSTREAMING          1094
    #define FACILITY_ TTD                     1490
    #define FACILITY_ ACCELERATOR             1536
    #define FACILITY_ WMAAECMA                1996
    #define FACILITY_ DIRECTMUSIC             2168
    #define FACILITY_ DIRECT3D10              2169
    #define FACILITY_ DXGI                    2170
    #define FACILITY_ DXGI_DDI                2171
    #define FACILITY_ DIRECT3D11              2172
    #define FACILITY_ DIRECT3D11_DEBUG        2173
    #define FACILITY_ DIRECT3D12              2174
    #define FACILITY_ DIRECT3D12_DEBUG        2175
    #define FACILITY_ DXCORE                  2176
    #define FACILITY_ LEAP                    2184
    #define FACILITY_ AUDCLNT                 2185
    #define FACILITY_ WINCODEC_DWRITE_DWM     2200
    #define FACILITY_ WINML                   2192
    #define FACILITY_ DIRECT2D                2201
    #define FACILITY_ DEFRAG                  2304
    #define FACILITY_ USERMODE_SDBUS          2305
    #define FACILITY_ JSCRIPT                 2306
    #define FACILITY_ PIDGENX                 2561
    #define FACILITY_ EAS                     85
    #define FACILITY_ WEB                     885
    #define FACILITY_ WEB_SOCKET              886
    #define FACILITY_ MOBILE                  1793
    #define FACILITY_ SQLITE                  1967
    #define FACILITY_ UTC                     1989
    #define FACILITY_ WEP                     2049
    #define FACILITY_ SYNCENGINE              2050
    #define FACILITY_ XBOX                    2339
    #define FACILITY_ GAME                    2340
    #define FACILITY_ PIX                     2748
}
